name: End-to-end tests

on:
  push:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  orangehrm-tests:
    name: OrangeHRM - Cypress Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: OrangeHRM

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests for OrangeHRM
        uses: cypress-io/github-action@v6
        with:
          working-directory: OrangeHRM

  swaglabs-tests:
    name: SwagLabs - Cypress Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: SwagLabs

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests for SwagLabs
        uses: cypress-io/github-action@v6
        with:
          working-directory: SwagLabs

  bugereats-tests:
    name: BugerEats - Cypress Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BugerEats

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests for BugerEats
        uses: cypress-io/github-action@v6
        with:
          working-directory: BugerEats
